service: cmr-stac-api

provider:
  name: aws
  runtime: nodejs10.x
  region: us-east-1
  role: cmrStacRole
  deploymentBucket: ${cf:${opt:stage}.cmrStacDeploymentBucket}
  vpc:
    securityGroupIds:
      - ${cf:${opt:stage}.servicesSecurityGroupId}
    subnetIds: !Split [ ",", "${cf:${opt:stage}.subnetIds}" ]

custom:
  cmrStacRelativeRootUrl: /cmr-stac
  cmrStacBaseUrl:
    sit: cmr.sit.earthdata.nasa.gov${self:custom.cmrStacRelativeRootUrl}
    uat: cmr.uat.earthdata.nasa.gov${self:custom.cmrStacRelativeRootUrl}
    prod: cmr.earthdata.nasa.gov${self:custom.cmrStacRelativeRootUrl}
    default: http://${cf:${opt:stage}.servicesDnsName}${self:custom.cmrStacRelativeRootUrl}

functions:
  search-api:
    name: cmr-stac-${opt:stage}
    handler: lib/application.handler
    events:
      - alb:
          listenerArn: ${cf:${opt:stage}.servicesLbListenerArn}
          priority: 84
          conditions:
            path: ${self:custom.cmrStacRelativeRootUrl}*
    environment:
      LOG_LEVEL: info
      LOG_DISABLED: false
      STAC_BASE_URL: ${self:custom.cmrStacBaseUrl.${opt:stage}, self:custom.cmrStacBaseUrl.default}
      STAC_VERSION: 0.8.0
      CMR_SEARCH_HOST: ${cf:${opt:stage}.servicesDnsName}
      CMR_SEARCH_RELATIVE_ROOT_URL: /search
      CMR_SEARCH_PROTOCOL : http
      CMR_STAC_RELATIVE_ROOT_URL: ${self:custom.cmrStacRelativeRootUrl}

resources:
  Resources:
    cmrStacRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: cmrStacRole-${opt:stage}
        PermissionsBoundary: arn:aws:iam::#{AWS::AccountId}:policy/NGAPShRoleBoundary
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            -
              Effect: "Allow"
              Principal:
                Service:
                  - "lambda.amazonaws.com"
              Action:
                - "sts:AssumeRole"
plugins:
  - serverless-pseudo-parameters
