Resources:
  ConceptIdCache:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: stac-conceptIdTable
      AttributeDefinitions:
        - AttributeName: stacId
          AttributeType: S
      KeySchema:
        - AttributeName: stacId
          KeyType: HASH
      TimeToLiveSpecification:
        AttributeName: expdate
        Enabled: true
      BillingMode: PAY_PER_REQUEST
