---
Resources:
  ConceptCache:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.cmrStacName}-conceptCacheTable
      AttributeDefinitions:
        - AttributeName: conceptId
          AttributeType: S
      KeySchema:
        - AttributeName: conceptId
          KeyType: HASH
      TimeToLiveSpecification:
        AttributeName: expdate
        Enabled: true
      BillingMode: PAY_PER_REQUEST
