name: STAC Tests

on:
  push:
    branches:
      - "master"
      - "[0-9]+\\.[0-9]+\\.[0-9]+-r[0-9]{2}\\.[0-9]\\.[0-9]"
      - "[0-9]+\\.[0-9]+\\.x"
      - "dev/**"
  pull_request:
    branches: ["master"]

jobs:
  UnitTests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        node_version: [18]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests with Coverage
        run: npm run test:coverage
        env:
          CI: true
